### ISSUE TITLE
Configurable verbosity level

### ISSUE THREAD

**Issue by sisp** [Mountlex/glap#2]
In particular, printing the list of downloaded files is quite long for me and not needed. I'm using `glap` in a CI job that downloads artifacts from several branches, so the CI log becomes quite long.

@Mountlex What do you think?

**Comment by Mountlex** [comment]
Hi @sisp, thanks for the suggestion. I will add silent / verbose flags in the next release.

**Comment by sisp** [comment]
Perfect, thank you very much! :slightly_smiling_face:
