### ISSUE TITLE
Support all authentication methods that python-gitlab supports

### ISSUE THREAD

**Issue by sisp** [Mountlex/glap#3]
In particular, I'd like to use `$CI_JOB_TOKEN` to authenticate with the GitLab API, however, `glap` currently only supports a private token.

I think you could replicate the same authentication options that `python-gitlab` offers, or simply delegate authentication to `python-gitlab`, i.e. a user who needs authentication needs to configure it via `python-gitlab`'s configuration file.

Edit: Actually, maybe adding the same configuration options to `glap.toml` is preferable to not expose the dependency on `python-gitlab` in case this ever changes.

@Mountlex What do you think?

**Comment by Mountlex** [comment]
Hi, I added the keys `job_token` and `oauth_token` to the configuration file, which get propagated to the `GitLab` instance. I also renamed the private token key to `private_token`. Thank you for the suggestion!

**Comment by sisp** [comment]
Perfect, thank you very much! :slightly_smiling_face:
