### ISSUE TITLE
Support downloading artifacts for tags

### ISSUE THREAD

**Issue by sisp** [Mountlex/glap#4]
As an alternative to specifying a branch name for which to download the corresponding CI job artifact, I'd like to be able to specify a tag name. Perhaps another flag `--tag` could be introduced that is mutually exclusive with `--branch`, so only of the two can ever be provided.

@Mountlex What do you think?

**Comment by Mountlex** [comment]
Hi @sisp, I changed the the `branch` option to a general `ref` option, which can either be a branch or a tag.

**Comment by sisp** [comment]
Hm, what happens if a branch and tag have the same name?

**Comment by Mountlex** [comment]
Hm I guess that `python-gitlab` propagates the `ref_name` parameter of the [`arifacts`-function](https://python-gitlab.readthedocs.io/en/stable/gl_objects/pipelines_and_jobs.html#jobs) through to [this GET request](https://docs.gitlab.com/ee/api/job_artifacts.html#download-the-artifacts-archive) of the GitLab API, which also doesn't specify this case. 

EDIT: It seems to be a general problem that tags can have the same names as branches, e.g. https://gitlab.com/gitlab-org/gitlab/-/issues/219583.

**Comment by sisp** [comment]
I think there is a way to differentiate between branch and tag artifacts, but it requires a few more API calls like getting the list of pipelines of the repository, filtering only successful pipelines, filtering the requested branch or tag, and downloading the artifact from the requested job of the filtered pipeline. It may not be worth the effort for now though. It's probably not a good idea to have equal branch and tag names anyway. I was just thinking to ensure correctness.

Thanks for adding the `ref` option.
